In [1]:
import pandas as pd

In [2]:
import os
os.chdir(os.path.pardir)

In [3]:
meteo_data = pd.read_csv('data/external/atlanta_rh_temp.csv')

In [9]:
meteo_data.index = pd.to_datetime(meteo_data['Date'])

                  Date  rh_max     rh_mean  temp_max  temp_mean
Date
2007-01-01  2007-01-01   100.0   80.375000      60.0  51.333333
2007-01-02  2007-01-02   100.0   71.875000      58.0  42.916667
2007-01-03  2007-01-03   100.0   82.020833      55.0  44.541667
2007-01-04  2007-01-04   100.0   82.250000      65.0  57.708334
2007-01-05  2007-01-05   100.0   96.416667      67.0  60.729167
2007-01-06  2007-01-06   100.0   86.500000      69.0  55.979167
2007-01-07  2007-01-07   100.0   97.812500      63.0  56.083333
2007-01-08  2007-01-08   100.0   65.020833      61.0  48.291667
2007-01-09  2007-01-09   100.0   64.229167      53.0  40.500000
2007-01-10  2007-01-10    91.0   56.958334      49.0  38.020833
2007-01-11  2007-01-11   100.0   60.479167      54.0  41.187500
2007-01-12  2007-01-12    98.0   71.708334      64.0  50.979167
2007-01-13  2007-01-13   100.0   84.312500      69.0  55.291667
2007-01-14  2007-01-14   100.0   81.958333      70.0  59.812500
2007-01-15  2007-01-15   100.0   84.958333      72.0  62.229167
2007-01-16  2007-01-16   100.0   85.020833      57.0  43.895834
2007-01-17  2007-01-17    90.0   62.812500      45.0  37.166667
2007-01-18  2007-01-18   100.0   95.500000      39.0  34.791667
2007-01-19  2007-01-19   100.0   71.562500      51.0  42.937500
2007-01-20  2007-01-20    67.0   49.208334      52.0  41.583333
2007-01-21  2007-01-21   100.0   76.458333      46.0  41.500000
2007-01-22  2007-01-22   100.0   92.916667      47.0  42.500000
2007-01-23  2007-01-23    86.0   75.708333      45.0  39.750000
2007-01-24  2007-01-24    90.0   70.312500      48.0  40.416667
2007-01-25  2007-01-25    83.0   61.645834      50.0  40.604167
2007-01-26  2007-01-26    84.0   51.395833      54.0  38.166667
2007-01-27  2007-01-27   100.0   59.625000      60.0  44.770834
2007-01-28  2007-01-28   100.0   69.812500      44.0  39.062500
2007-01-29  2007-01-29    71.0   49.187500      40.0  28.083333
2007-01-30  2007-01-30    87.0   52.979167      51.0  38.187500
...                ...     ...         ...       ...        ...
2019-01-02  2019-01-02   100.0   96.541667      59.0  52.791667
2019-01-03  2019-01-03   100.0  100.000000      55.0  52.916667
2019-01-04  2019-01-04   100.0   92.217391      63.0  54.391304
2019-01-05  2019-01-05    83.0   69.125000      59.0  48.958333
2019-01-06  2019-01-06    96.0   70.750000      69.0  51.708333
2019-01-07  2019-01-07    99.0   74.750000      69.0  51.500000
2019-01-08  2019-01-08    98.0   85.500000      63.0  54.208333
2019-01-09  2019-01-09    65.0   39.958333      55.0  47.250000
2019-01-10  2019-01-10    70.0   51.916667      46.0  36.916667
2019-01-11  2019-01-11    89.0   58.625000      53.0  39.416667
2019-01-12  2019-01-12    99.0   66.166667      43.0  40.500000
2019-01-13  2019-01-13    99.0   96.583333      46.0  40.291667
2019-01-14  2019-01-14    92.0   80.208333      47.0  43.875000
2019-01-15  2019-01-15    90.0   73.333333      47.0  38.875000
2019-01-16  2019-01-16    96.0   76.583333      54.0  39.166667
2019-01-17  2019-01-17   100.0   93.875000      49.0  40.166667
2019-01-18  2019-01-18   100.0   97.500000      57.0  49.541667
2019-01-19  2019-01-19   100.0  100.000000      61.0  54.826087
2019-01-20  2019-01-20   100.0   69.333333      51.0  36.291667
2019-01-21  2019-01-21    70.0   48.333333      43.0  31.916667
2019-01-22  2019-01-22    52.0   41.875000      46.0  37.750000
2019-01-23  2019-01-23   100.0   72.125000      68.0  54.083333
2019-01-24  2019-01-24   100.0   82.625000      55.0  42.958333
2019-01-25  2019-01-25    86.0   63.541667      48.0  37.250000
2019-01-26  2019-01-26    92.0   70.041667      51.0  36.625000
2019-01-27  2019-01-27    97.0   81.125000      51.0  38.708333
2019-01-28  2019-01-28    98.0   70.708333      58.0  43.791667
2019-01-29  2019-01-29    97.0   68.375000      51.0  41.250000
2019-01-30  2019-01-30    77.0   52.375000      44.0  32.416667
2019-01-31  2019-01-31    90.0   62.666667      51.0  35.958333

[4414 rows x 5 columns]